# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=postgres
export POSTGRES_PASSWORD=postgres
export POSTGRES_HOST=database1.cbxud0ta9wwk.us-east-1.rds.amazonaws.com
export POSTGRES_DB=postgres
export AWS_BUCKET=arn:aws:s3:::leenah1
export AWS_REGION=us-east-1
export AWS_PROFILE=default
export JWT_SECRET=mysecretstring
export URL=http://localhost:8100
export AWS_SECRET_ACCESS_KEY=be2ygtY5SEQPjyhFaHz4PISbdh31aZy5UjG7Z0GD
export AWS_ACCESS_KEY_ID=ASIA4GFKV7Z3AUZ4XQNR
export AWS_SESSION_TOKEN=FwoGZXIvYXdzEMb//////////wEaDNXqQ2cSVfJZfdFyGyLVAdEZ2P9MCTQAGV7ATQ34s0FfRx3cFpXymlUNflfW7yicIABChFODNuNYkB8e9b/LqrHfBoSvzZOHwWR0daNIh8JCRv6/TOP6UsyDZaNaFZ/dEyfG3yQPcDRWDxprnA0jKuld0VldtliFjU54jfEiuiE9PV3oqvw8I3SWYUAnkFAVRAgdQOsWT/luPGtrZFMVq1zfRhWIH8YpWQ9fUNAy/EBo072RO4Jtc2+75xuQSG61NgPjINBGJ+C7WmjHiYpnioOugYvENDTmESOQQVQUNoXZPikz7iiEuvKfBjIt4yBDtV/Gn4Eg9hVjtFPI8iyP9gDmmnQC08Kps0Hr168zCSy+YogrAaozY4HJ